AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image processing pipeline using S3, SQS, Lambda, DynamoDB, and DLQ

Resources:
  ImageProcessingBucket:
    Type: AWS::S3::Bucket

  ImageProcessingQueue:
    Type: AWS::SQS::Queue

  ImageProcessingDLQ:
    Type: AWS::SQS::Queue

  ImageProcessingRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: image_id
          AttributeType: S
      KeySchema:
        - AttributeName: image_id
          KeyType: HASH

  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dave-image-processing-function
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: ../../src/process_image/
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageProcessingRecordsTable
