AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image processing pipeline using S3, SQS, Lambda, DynamoDB, and DLQ

Resources:
  ImageProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ImageProcessingQueue.Arn  

  ImageProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageProcessingDLQ.Arn
        maxReceiveCount: 3
        
  ImageProcessingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ImageProcessingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3SendMessage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt ImageProcessingQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt ImageProcessingBucket.Arn

  ImageProcessingDLQ:
    Type: AWS::SQS::Queue

  ImageProcessingRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: image_id
          AttributeType: S
      KeySchema:
        - AttributeName: image_id
          KeyType: HASH

  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dave-image-processing-function
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: ../../src/process_image/
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageProcessingRecordsTable
        - S3ReadPolicy:
            BucketName: !Ref ImageProcessingBucket
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageProcessingQueue.Arn
            BatchSize: 1         
